export const products = [
  {
    id: "1",
    title: "Samsung Galaxy S20",
    price: "USD 400",
    image: require("../assets/s20.jpg"),
    images: [
      require("../assets/s20.jpg"),
      require("../assets/desktop.jpeg"),
      require("../assets/laptop.jpeg"),
    ],
    seller: { id: "101", name: "Tech Store" },
  },
  {
    id: "2",
    title: "Nike Air Max",
    price: "USD 80",
    image: require("../assets/shoes.jpeg"),
    images: [
      require("../assets/shoes.jpeg"),
      require("../assets/bag.jpeg"),
      require("../assets/jeans.jpeg"),
    ],
    seller: { id: "102", name: "Sneaker Hub" },
  },
  {
    id: "3",
    title: "Leather Bag",
    price: "USD 55",
    image: require("../assets/bag.jpeg"),
    images: [
      require("../assets/bag.jpeg"),
      require("../assets/khakhi.jpeg"),
      require("../assets/jeans.jpeg"),
    ],
    seller: { id: "103", name: "City Styles" },
  },
  {
    id: "4",
    title: "Family Car",
    price: "USD 4200",
    image: require("../assets/car.jpeg"),
    images: [
      require("../assets/car.jpeg"),
      require("../assets/house.jpeg"),
      require("../assets/fc26.jpeg"),
    ],
    seller: { id: "104", name: "Auto Deals" },
  },
  {
    id: "5",
    title: "Office Chair",
    price: "USD 70",
    image: require("../assets/chair.jpeg"),
    images: [
      require("../assets/chair.jpeg"),
      require("../assets/desk.jpeg"),
      require("../assets/sofa.jpeg"),
    ],
    seller: { id: "105", name: "FurniShop" },
  },
  {
    id: "6",
    title: "Study Desk",
    price: "USD 120",
    image: require("../assets/desk.jpeg"),
    images: [
      require("../assets/desk.jpeg"),
      require("../assets/desktop.jpeg"),
      require("../assets/laptop.jpeg"),
    ],
    seller: { id: "105", name: "FurniShop" },
  },
  {
    id: "7",
    title: "Desktop PC",
    price: "USD 500",
    image: require("../assets/desktop.jpeg"),
    images: [
      require("../assets/desktop.jpeg"),
      require("../assets/laptop.jpeg"),
      require("../assets/hero_image.jpg"),
    ],
    seller: { id: "106", name: "Compute World" },
  },
  {
    id: "8",
    title: "Modern House",
    price: "USD 120000",
    image: require("../assets/house.jpeg"),
    images: [
      require("../assets/house.jpeg"),
      require("../assets/wardrobe.jpeg"),
      require("../assets/sofa.jpeg"),
    ],
    seller: { id: "107", name: "Homes Hub" },
  },
  {
    id: "9",
    title: "Blue Jeans",
    price: "USD 25",
    image: require("../assets/jeans.jpeg"),
    images: [
      require("../assets/jeans.jpeg"),
      require("../assets/khakhi.jpeg"),
      require("../assets/bag.jpeg"),
    ],
    seller: { id: "108", name: "Denim Co" },
  },
  {
    id: "10",
    title: "Khakhi Pants",
    price: "USD 22",
    image: require("../assets/khakhi.jpeg"),
    images: [
      require("../assets/khakhi.jpeg"),
      require("../assets/jeans.jpeg"),
      require("../assets/shoes.jpeg"),
    ],
    seller: { id: "108", name: "Denim Co" },
  },
  {
    id: "11",
    title: "Dell Laptop",
    price: "USD 650",
    image: require("../assets/laptop.jpeg"),
    images: [
      require("../assets/laptop.jpeg"),
      require("../assets/desktop.jpeg"),
      require("../assets/desk.jpeg"),
    ],
    seller: { id: "106", name: "Compute World" },
  },
  {
    id: "12",
    title: "Comfy Sofa",
    price: "USD 260",
    image: require("../assets/sofa.jpeg"),
    images: [
      require("../assets/sofa.jpeg"),
      require("../assets/chair.jpeg"),
      require("../assets/wardrobe.jpeg"),
    ],
    seller: { id: "105", name: "FurniShop" },
  },
  {
    id: "13",
    title: "Wardrobe",
    price: "USD 180",
    image: require("../assets/wardrobe.jpeg"),
    images: [
      require("../assets/wardrobe.jpeg"),
      require("../assets/chair.jpeg"),
      require("../assets/sofa.jpeg"),
    ],
    seller: { id: "105", name: "FurniShop" },
  },
  {
    id: "14",
    title: "Feature Phone FC26",
    price: "USD 35",
    image: require("../assets/fc26.jpeg"),
    images: [
      require("../assets/fc26.jpeg"),
      require("../assets/s20.jpg"),
      require("../assets/desktop.jpeg"),
    ],
    seller: { id: "101", name: "Tech Store" },
  },
  {
    id: "15",
    title: "Hero Poster",
    price: "USD 10",
    image: require("../assets/hero_image.jpg"),
    images: [
      require("../assets/hero_image.jpg"),
      require("../assets/bag.jpeg"),
      require("../assets/chair.jpeg"),
    ],
    seller: { id: "109", name: "Print Lab" },
  },
];
  